package com.bitspace.food.base;

public enum EventType {

    RESPONSE,PRIORITY_NOTIFICATION,
    //user
    USER_UPDATE_DB,USER_REGISTER,USER_INSERT_DB,UPDATE_PWD,UPDATE_PRICE_PWD,USER_OPEN,

    //personal


    //goods
    ADMIN_GOODS_LIST,ADMIN_GOODS_INFO,ADMIN_GOODS_UPDATE_PAYPWD,
    ADMIN_GOODS_INSET_MEMO,ADMIN_GOODS_INSET, ADMIN_AUDIT_GOODS,ADMIN_RECALL_GOODS,ADMIN_UPDATE_GOODS,
    ADMIN_SUPPLIER_OUT,ADMIN_DEALER_OUT,ADMIN_CIRCULATE_HISTORY_LIST_BY_GOODSID,ADMIN_GET_ACCUSATION_HISTORY_LIST,
    ADMIN_BANCH_DISPOSE_ACCUSATION,ADMIN_PERFECT_GOODS,ADMIN_SUPPLIER_INDEX_COUNT,ADMIN_DEALER_INDEX_COUNT,
    ADMIN_MONITOR_INDEX_COUNT,GOODS_DETAIL_CODE,ADMIN_INSERT_ACCUSATION_HISTORY,ADMIN_CIRCULATE_HISTORY_LIST_BY_HASHID,
    ADMIN_CIRCULATE_HISTORY_LIST_BY_NEW,ADMIN_BLOCK_HEIGHT,

    //merchant
    ADMIN_MERCHANT_MANAGE_LIST,ADMIN_MERCHANT_FROZEN,ADMIN_MERCHANT_AUDIT,

    //captcha
    CAPTCHA_GENERATE, CAPTCHA_CHECK, CAPTCHA_SMS_SEND, CAPTCHA_IMGCODE_GENERATE, CAPTCHA_IMGCODE_CHECK,


    //account
    CREATE_WALLET,WALLET_TRANSFER,CREATE_GOODS,CREATE_GOODS_REPORTS,CREATE_GOODS_HISTORY,CREATE_GOODS_MEMO,

    //currency


    //account db

    // user_currency_history
    HTTP_COMMON,
    
    //admin
    HTTP_RESOLVE_COMMON,ADMIN_REGISTER,ADMIN_FROZEN_ADMIN,ADMIN_INSERT_DB,ADMIN_UPDATE_PAYPWD,

    // announcement
    ANNOUNCEMENT_LIST, ANNOUNCEMENT_DETAIL_LIST, ANNOUNCEMENT_GET_BYID,ANNOUNCEMENT_GET_BODY, ANNOUNCEMENT_ADD, ANNOUNCEMENT_CLOSE, ANNOUNCEMENT_DELETE

}
