server:
   port: 9101

#spring.datasource.url=jdbc:mysql://10.88.88.116:3306/food?useSSL=false&characterEncoding=utf8&useAffectedRows=true
spring:
  datasource:
    url: jdbc:mysql://10.88.88.116:3306/food?useSSL=false&characterEncoding=utf8&useAffectedRows=true
    username: food
    password: food


logging:
    level: info
    #config: src/main/resources/log4j2.sample.xml
    file: logs/food.log

#db-config:
#host: 10.88.88.116
#port: 3306
#name: food
#user: root
#password: root

jwt:
  tokenHeader: food-token
  secretKey: ae2st4F3fdsaf32$65
  keyPrefix: food
  expireTime: 86400000

  registerRpcUrl: http://test.vac.zone/vac/createwallet  #上链创建账号
  sendxrpUrl: http://test.vac.zone/vac/sendxrp  #上链转账
  sourceAddress: rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh
  sourcePassword: snoPBrXtMeMyMHUVTgbuqAfg1SUTb
  addGoodsToChainUrl: http://test.vac.zone/vac/submit #商品上链



